### ISSUE TITLE
chakra&storybook

### ISSUE THREAD

**Issue by prifina-admin** [darshan420/eco-knowledge#1]
Seems new version of chakra breaks something with storybook... looks like emotion package version problem. The Chakraprovider is not handling theme correct way.  Weird there is not so much info about this issue... I guess there are not so many new version users yet. 

Replace the main.js with this can help .... 

const path = require("path");
const toPath = (_path) => path.join(process.cwd(), _path);

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
  ],
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": toPath("node_modules/@emotion/react"),
          "emotion-theming": toPath("node_modules/@emotion/react"),
        },
      },
    };
  },
};

**Comment by darshan420** [comment]
Issue solved
